### PR TITLE
#74: Set length of USER_ORGANIZATION_ROLE_MAPPING.ROLE_ID to 36 to match ForeignKey ORGANIZATION_ROLE.ID

### LINKED ISSUE #74: Column 'ORGANIZATION_ROLE.ID' is not the same length or scale as referencing column 'USER_ORGANIZATION_ROLE_MAPPING.ROLE_ID'
Hello,

I'm implementing the Keycloak organization for our project. Our project uses mssql and this seems create an error. When I build a docker image based on quay.io/phasetwo/phasetwo-keycloak:latest and run it I get the following error:

Reason: liquibase.exception.DatabaseException: Column 'ORGANIZATION_ROLE.ID' is not the same length or scale as referencing column 'USER_ORGANIZATION_ROLE_MAPPING.ROLE_ID' in foreign key 'FK_123g9nf5findslfksadifu277'. Columns participating in a foreign key relationship must be defined with the same length and scale. [Failed SQL: (1753) ALTER TABLE USER_ORGANIZATION_ROLE_MAPPING ADD CONSTRAINT FK_123g9nf5findslfksadifu277 FOREIGN KEY (ROLE_ID) REFERENCES ORGANIZATION_ROLE (ID)]

It seems that the USER_ORGANIZATION_ROLE_MAPPING.ROLE_ID has a length of 255 and ORGANIZATION_ROLE.ID has a length of 36.

See: https://github.com/p2-inc/keycloak-orgs/blob/e61c9c0a5119d5e731b78509ad7abdeecc544dbb/src/main/resources/META-INF/jpa-changelog-phasetwo-20200424.xml#L5

@Column(name = "ID", length = 36):
https://github.com/p2-inc/keycloak-orgs/blob/e61c9c0a5119d5e731b78509ad7abdeecc544dbb/src/main/java/io/phasetwo/service/model/jpa/entity/OrganizationRoleEntity.java#L31

@JoinColumn(name = "ROLE_ID") -> no length which I guess results in a default 255:
https://github.com/p2-inc/keycloak-orgs/blob/e61c9c0a5119d5e731b78509ad7abdeecc544dbb/src/main/java/io/phasetwo/service/model/jpa/entity/UserOrganizationRoleMappingEntity.java#L64

Could the length of the USER_ORGANIZATION_ROLE_MAPPING.ROLE_ID be changed to 36?

Thanks!

### PR DESCRIPTION
**Pull request by Panickev**
Fixes #74

### CODE REVIEW

**Comment by Panickev** [comment]
I'm not really familliar with this so Im not sure if I've done it correctly. I've added jpa-changelog-phasetwo-20230517.xml for the data-migration of the column length.

**Comment by xgp** [comment]
I think this is fine. We need to run regression tests on all the DBs we support, just to make sure, but I'll merge it after we do that. Thank you!

**Comment by Panickev** [comment]
I was just looking through the datamigrations and I found this:
https://github.com/p2-inc/keycloak-orgs/pull/57

This seems to do the same thing I'm trying to do, set ROLE_ID to VARCHAR(36)

When I run keycloak and I look in the DATABASECHANGELOG_ORGANIZATI I do not see the META-INF/jpa-changelog-phasetwo-20211206.xml fiel as ran. I use quay.io/phasetwo/phasetwo-keycloak:21.0.1.1679927321. Is this the correct one?

**Comment by xgp** [comment]
Thanks for looking into this. If you haven't already tested/validated against the most recent tag `21.1.1.1683924709`, please do that and see if it fixes your problem. @grinay contributed mssql support recently, so it will not be in earlier tags.

**Comment by Panickev** [comment]
Ah ye sthat version does seem to work. Thanks! I will close this MR.

**Pull request closed without merging**
